# code: language=ansible
---
- name: Base configurations
  hosts: localhost
  connection: local
  tasks:
    - name: System configs
      ansible.builtin.include_tasks: tasks/system_config.tasks.yml
...
