# code: language=ansible
---
- name: Install flatpaks
  community.general.flatpak:
    name:
      # browser
      - app.zen_browser.zen
      # social
      - org.gnome.Fractal
      - org.telegram.desktop
      - com.discordapp.Discord
      - com.slack.Slack
      # media
      - io.github.nokse22.high-tide
      - org.pipewire.Helvum
      - com.saivert.pwvucontrol
      - tv.plex.PlexDesktop
      - com.github.iwalton3.jellyfin-media-player
      # utility
      - org.deskflow.deskflow
      - me.proton.Pass
      - me.proton.Mail
      - com.protonvpn.www
      - org.gnome.Extensions
      - com.usebottles.bottles
...
